// <auto-generated />
using System;
using ChristmasLottery.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChristmasLottery.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241107195837_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ChristmasLottery.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GiftForUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wants")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiftForUserId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("ChristmasLottery.UserData", b =>
                {
                    b.HasOne("ChristmasLottery.UserData", "GiftForUser")
                        .WithMany()
                        .HasForeignKey("GiftForUserId");

                    b.Navigation("GiftForUser");
                });
#pragma warning restore 612, 618
        }
    }
}
